import type { AttendanceRecord } from "@/types";

export const attendanceRecords: AttendanceRecord[] = [
  {
    id: "att-001",
    staffId: "usr-006",
    staffName: "Murugan P",
    staffRole: "MECHANIC",
    branchId: "br-001",
    date: "2026-03-18",
    checkIn: "09:00",
    checkOut: "18:00",
    durationMinutes: 540,
    status: "PRESENT",
    qrScanned: true,
  },
  {
    id: "att-002",
    staffId: "usr-007",
    staffName: "Ramesh Gowda",
    staffRole: "MECHANIC",
    branchId: "br-001",
    date: "2026-03-18",
    checkIn: "09:45",
    checkOut: "18:30",
    durationMinutes: 525,
    status: "LATE",
    qrScanned: true,
  },
  {
    id: "att-003",
    staffId: "usr-008",
    staffName: "Karthik Iyer",
    staffRole: "MECHANIC",
    branchId: "br-001",
    date: "2026-03-18",
    checkIn: "08:55",
    checkOut: "17:45",
    durationMinutes: 530,
    status: "PRESENT",
    qrScanned: true,
  },
  {
    id: "att-004",
    staffId: "usr-004",
    staffName: "Anitha Nair",
    staffRole: "RECEPTIONIST",
    branchId: "br-001",
    date: "2026-03-18",
    checkIn: "09:15",
    checkOut: undefined,
    durationMinutes: undefined,
    status: "HALF_DAY",
    qrScanned: true,
  },
  {
    id: "att-005",
    staffId: "usr-003",
    staffName: "Suresh Reddy",
    staffRole: "MANAGER",
    branchId: "br-001",
    date: "2026-03-18",
    checkIn: undefined,
    checkOut: undefined,
    durationMinutes: undefined,
    status: "ABSENT",
    qrScanned: false,
  },
  {
    id: "att-006",
    staffId: "usr-001",
    staffName: "Rajesh Kumar",
    staffRole: "ADMIN",
    branchId: "br-001",
    date: "2026-03-17",
    checkIn: "09:00",
    checkOut: "18:00",
    durationMinutes: 540,
    status: "PRESENT",
    qrScanned: true,
  },
  {
    id: "att-007",
    staffId: "usr-006",
    staffName: "Murugan P",
    staffRole: "MECHANIC",
    branchId: "br-001",
    date: "2026-03-17",
    checkIn: "09:30",
    checkOut: "18:00",
    durationMinutes: 510,
    status: "LATE",
    qrScanned: true,
  },
  {
    id: "att-008",
    staffId: "usr-007",
    staffName: "Ramesh Gowda",
    staffRole: "MECHANIC",
    branchId: "br-001",
    date: "2026-03-17",
    checkIn: "08:50",
    checkOut: "17:30",
    durationMinutes: 520,
    status: "PRESENT",
    qrScanned: true,
  },
  {
    id: "att-009",
    staffId: "usr-008",
    staffName: "Karthik Iyer",
    staffRole: "MECHANIC",
    branchId: "br-001",
    date: "2026-03-17",
    checkIn: undefined,
    checkOut: undefined,
    durationMinutes: undefined,
    status: "ABSENT",
    qrScanned: false,
  },
  {
    id: "att-010",
    staffId: "usr-004",
    staffName: "Anitha Nair",
    staffRole: "RECEPTIONIST",
    branchId: "br-001",
    date: "2026-03-16",
    checkIn: "09:00",
    checkOut: "18:00",
    durationMinutes: 540,
    status: "PRESENT",
    qrScanned: true,
  },
];
