import type { SalaryStructure } from "@/types";

/** Default salary matrices: role × experience band (demo). */
export const seedSalaryStructures: SalaryStructure[] = [
  {
    id: "ss-mech-entry",
    role: "MECHANIC",
    experienceBand: "ENTRY",
    label: "Mechanic · Entry (0–1 yr)",
    baseSalary: 18500,
    attendanceBonusPerDay: 150,
    absenceDeductionPerDay: 450,
  },
  {
    id: "ss-mech-mid",
    role: "MECHANIC",
    experienceBand: "MID",
    label: "Mechanic · Mid (1–3 yr)",
    baseSalary: 24000,
    attendanceBonusPerDay: 200,
    absenceDeductionPerDay: 550,
  },
  {
    id: "ss-mech-senior",
    role: "MECHANIC",
    experienceBand: "SENIOR",
    label: "Mechanic · Senior (3+ yr)",
    baseSalary: 31000,
    attendanceBonusPerDay: 250,
    absenceDeductionPerDay: 600,
  },
  {
    id: "ss-mech-lead",
    role: "MECHANIC",
    experienceBand: "LEAD",
    label: "Mechanic · Lead technician",
    baseSalary: 38000,
    attendanceBonusPerDay: 300,
    absenceDeductionPerDay: 650,
  },
  {
    id: "ss-rec-entry",
    role: "RECEPTIONIST",
    experienceBand: "ENTRY",
    label: "Receptionist · Entry",
    baseSalary: 16000,
    attendanceBonusPerDay: 100,
    absenceDeductionPerDay: 400,
  },
  {
    id: "ss-rec-mid",
    role: "RECEPTIONIST",
    experienceBand: "MID",
    label: "Receptionist · Experienced",
    baseSalary: 20000,
    attendanceBonusPerDay: 120,
    absenceDeductionPerDay: 480,
  },
  {
    id: "ss-mgr-mid",
    role: "MANAGER",
    experienceBand: "MID",
    label: "Manager · Standard",
    baseSalary: 42000,
    attendanceBonusPerDay: 0,
    absenceDeductionPerDay: 800,
  },
  {
    id: "ss-mgr-senior",
    role: "MANAGER",
    experienceBand: "SENIOR",
    label: "Manager · Senior",
    baseSalary: 52000,
    attendanceBonusPerDay: 0,
    absenceDeductionPerDay: 1000,
  },
  {
    id: "ss-admin-senior",
    role: "ADMIN",
    experienceBand: "SENIOR",
    label: "Admin / Company lead",
    baseSalary: 65000,
    attendanceBonusPerDay: 0,
    absenceDeductionPerDay: 1200,
  },
  {
    id: "ss-super-admin-senior",
    role: "SUPER_ADMIN",
    experienceBand: "SENIOR",
    label: "Super Admin",
    baseSalary: 90000,
    attendanceBonusPerDay: 0,
    absenceDeductionPerDay: 0,
  },
  {
    id: "ss-bm-mid",
    role: "BRANCH_MANAGER",
    experienceBand: "MID",
    label: "Branch Manager · Standard",
    baseSalary: 48000,
    attendanceBonusPerDay: 0,
    absenceDeductionPerDay: 900,
  },
  {
    id: "ss-bm-senior",
    role: "BRANCH_MANAGER",
    experienceBand: "SENIOR",
    label: "Branch Manager · Senior",
    baseSalary: 56000,
    attendanceBonusPerDay: 0,
    absenceDeductionPerDay: 1000,
  },
  {
    id: "ss-supervisor-mid",
    role: "SUPERVISOR",
    experienceBand: "MID",
    label: "Supervisor · Floor lead",
    baseSalary: 28000,
    attendanceBonusPerDay: 180,
    absenceDeductionPerDay: 520,
  },
  {
    id: "ss-supervisor-senior",
    role: "SUPERVISOR",
    experienceBand: "SENIOR",
    label: "Supervisor · Senior",
    baseSalary: 34000,
    attendanceBonusPerDay: 220,
    absenceDeductionPerDay: 580,
  },
];
