import type { ServiceCatalogItem } from "@/types";

export const serviceCatalog: ServiceCatalogItem[] = [
  // --- General Service ---
  {
    id: "svc-001",
    name: "Oil Change",
    description: "Engine oil replacement with oil filter",
    defaultPrice: 1500,
    segmentPricing: {
      HATCHBACK: 1200,
      SEDAN: 1500,
      SUV: 2000,
      LUXURY: 3500,
      MUV: 2200,
      COMPACT_SUV: 1800,
    },
    category: "General Service",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 3,
    consumptionProfile: [
      { partId: "prt-001", partName: "Engine Oil 5W-30 (1L)", quantityPerCar: 1, unit: "L" },
      { partId: "prt-003", partName: "Oil Filter - Universal", quantityPerCar: 1, unit: "NOS" },
    ],
  },
  {
    id: "svc-002",
    name: "Full Service",
    description: "Complete vehicle servicing including oil, filters, fluid checks",
    defaultPrice: 5000,
    segmentPricing: {
      HATCHBACK: 4000,
      SEDAN: 5000,
      SUV: 6500,
      LUXURY: 9500,
      MUV: 7200,
      COMPACT_SUV: 5800,
    },
    category: "General Service",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 4,
    consumptionProfile: [
      { partId: "prt-001", partName: "Engine Oil 5W-30 (1L)", quantityPerCar: 3, unit: "L" },
      { partId: "prt-003", partName: "Oil Filter - Universal", quantityPerCar: 1, unit: "NOS" },
      { partId: "prt-004", partName: "Air Filter - Maruti", quantityPerCar: 1, unit: "NOS" },
      { partId: "prt-015", partName: "Cabin Air Filter", quantityPerCar: 1, unit: "NOS" },
      { partId: "prt-016", partName: "Coolant 1L - Green", quantityPerCar: 1, unit: "L" },
    ],
  },
  {
    id: "svc-003",
    name: "Minor Service",
    description: "Basic service - oil change, filter replacement, fluid top-up",
    defaultPrice: 2800,
    segmentPricing: {
      HATCHBACK: 2200,
      SEDAN: 2800,
      SUV: 3600,
      LUXURY: 5500,
      MUV: 4000,
      COMPACT_SUV: 3200,
    },
    category: "General Service",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 3,
    consumptionProfile: [
      { partId: "prt-001", partName: "Engine Oil 5W-30 (1L)", quantityPerCar: 2, unit: "L" },
      { partId: "prt-003", partName: "Oil Filter - Universal", quantityPerCar: 1, unit: "NOS" },
    ],
  },
  // --- Engine ---
  {
    id: "svc-004",
    name: "Engine Tune-up",
    description: "Spark plug replacement, ignition system check",
    defaultPrice: 3500,
    segmentPricing: {
      HATCHBACK: 2800,
      SEDAN: 3500,
      SUV: 4500,
      LUXURY: 7000,
      MUV: 5000,
      COMPACT_SUV: 4000,
    },
    category: "Engine",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 4,
    consumptionProfile: [
      { partId: "prt-009", partName: "Spark Plug - Iridium", quantityPerCar: 4, unit: "NOS" },
    ],
  },
  // --- Brakes ---
  {
    id: "svc-005",
    name: "Brake Pad Replacement",
    description: "Front & rear brake pad replacement",
    defaultPrice: 4500,
    segmentPricing: {
      HATCHBACK: 3600,
      SEDAN: 4500,
      SUV: 5800,
      LUXURY: 8500,
      MUV: 6200,
      COMPACT_SUV: 5000,
    },
    category: "Brakes",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 4,
    consumptionProfile: [
      { partId: "prt-006", partName: "Brake Pad Set - Front", quantityPerCar: 1, unit: "NOS" },
      { partId: "prt-007", partName: "Brake Pad Set - Rear", quantityPerCar: 1, unit: "NOS" },
    ],
  },
  {
    id: "svc-006",
    name: "Brake Disc Resurfacing",
    description: "Brake disc machining for smooth braking",
    defaultPrice: 2200,
    segmentPricing: {
      HATCHBACK: 1800,
      SEDAN: 2200,
      SUV: 2800,
      LUXURY: 4200,
      MUV: 3000,
      COMPACT_SUV: 2500,
    },
    category: "Brakes",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 3,
  },
  // --- AC ---
  {
    id: "svc-007",
    name: "AC Gas Refill",
    description: "R134a refrigerant recharge for AC system",
    defaultPrice: 2500,
    segmentPricing: {
      HATCHBACK: 2000,
      SEDAN: 2500,
      SUV: 3200,
      LUXURY: 4800,
      MUV: 3500,
      COMPACT_SUV: 2800,
    },
    category: "AC",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 3,
    consumptionProfile: [
      { partId: "prt-014", partName: "R134a Refrigerant (500g)", quantityPerCar: 1, unit: "NOS" },
    ],
  },
  {
    id: "svc-008",
    name: "AC Compressor Repair",
    description: "AC compressor diagnosis and repair",
    defaultPrice: 8500,
    segmentPricing: {
      HATCHBACK: 7000,
      SEDAN: 8500,
      SUV: 11000,
      LUXURY: 16000,
      MUV: 12000,
      COMPACT_SUV: 9500,
    },
    category: "AC",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 5,
    consumptionProfile: [
      { partId: "prt-013", partName: "AC Compressor Oil", quantityPerCar: 250, unit: "ML" },
    ],
  },
  // --- Electrical ---
  {
    id: "svc-009",
    name: "Battery Replacement",
    description: "Car battery replacement with installation",
    defaultPrice: 5500,
    segmentPricing: {
      HATCHBACK: 4500,
      SEDAN: 5500,
      SUV: 7200,
      LUXURY: 10500,
      MUV: 7800,
      COMPACT_SUV: 6200,
    },
    category: "Electrical",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 4,
    consumptionProfile: [
      { partId: "prt-011", partName: "Car Battery 12V 65Ah", quantityPerCar: 1, unit: "NOS" },
    ],
  },
  {
    id: "svc-010",
    name: "Alternator Repair",
    description: "Alternator diagnosis and repair",
    defaultPrice: 6500,
    segmentPricing: {
      HATCHBACK: 5200,
      SEDAN: 6500,
      SUV: 8500,
      LUXURY: 12500,
      MUV: 9200,
      COMPACT_SUV: 7400,
    },
    category: "Electrical",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 5,
    consumptionProfile: [
      { partId: "prt-012", partName: "Alternator Belt", quantityPerCar: 1, unit: "NOS" },
    ],
  },
  // --- Body ---
  {
    id: "svc-011",
    name: "Dent Repair",
    description: "Minor dent removal and panel beating",
    defaultPrice: 3000,
    segmentPricing: {
      HATCHBACK: 2400,
      SEDAN: 3000,
      SUV: 3900,
      LUXURY: 5800,
      MUV: 4200,
      COMPACT_SUV: 3400,
    },
    category: "Body",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 4,
  },
  {
    id: "svc-012",
    name: "Paint Touch-up",
    description: "Scratch and chip paint repair",
    defaultPrice: 2000,
    segmentPricing: {
      HATCHBACK: 1600,
      SEDAN: 2000,
      SUV: 2600,
      LUXURY: 3800,
      MUV: 2800,
      COMPACT_SUV: 2200,
    },
    category: "Body",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 3,
  },
  // --- Tires ---
  {
    id: "svc-013",
    name: "Tire Rotation",
    description: "Rotate all four tires for even wear",
    defaultPrice: 400,
    segmentPricing: {
      HATCHBACK: 350,
      SEDAN: 400,
      SUV: 500,
      LUXURY: 750,
      MUV: 550,
      COMPACT_SUV: 450,
    },
    category: "Tires",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 2,
  },
  {
    id: "svc-014",
    name: "Wheel Alignment",
    description: "Four-wheel alignment and balancing",
    defaultPrice: 1200,
    segmentPricing: {
      HATCHBACK: 1000,
      SEDAN: 1200,
      SUV: 1500,
      LUXURY: 2200,
      MUV: 1600,
      COMPACT_SUV: 1300,
    },
    category: "Tires",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 3,
  },
  {
    id: "svc-015",
    name: "Tire Replacement",
    description: "Tire replacement (per tire, excluding tire cost)",
    defaultPrice: 300,
    segmentPricing: {
      HATCHBACK: 250,
      SEDAN: 300,
      SUV: 400,
      LUXURY: 600,
      MUV: 450,
      COMPACT_SUV: 350,
    },
    category: "Tires",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 2,
  },
  // --- Detailing (New) ---
  {
    id: "svc-016",
    name: "Normal Wash",
    description:
      "Basic cleaning — water + small amount of shampoo. Takes less time. Shampoo usage: low (~8–10 ml per car).",
    defaultPrice: 250,
    segmentPricing: {
      HATCHBACK: 200,
      SEDAN: 250,
      SUV: 300,
      LUXURY: 500,
      MUV: 350,
      COMPACT_SUV: 280,
    },
    category: "Detailing",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 2,
    consumptionProfile: [
      { partId: "prt-021", partName: "Car Shampoo", quantityPerCar: 9, unit: "ML" },
    ],
  },
  {
    id: "svc-017",
    name: "Advanced Wash",
    description:
      "Better than normal — foam wash + proper wiping; may include tyre cleaning. Shampoo usage: medium (~12–18 ml per car).",
    defaultPrice: 600,
    segmentPricing: {
      HATCHBACK: 500,
      SEDAN: 600,
      SUV: 750,
      LUXURY: 1200,
      MUV: 850,
      COMPACT_SUV: 680,
    },
    category: "Detailing",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 2,
    consumptionProfile: [
      { partId: "prt-021", partName: "Car Shampoo", quantityPerCar: 15, unit: "ML" },
      { partId: "prt-022", partName: "Car Polish Wax (1L)", quantityPerCar: 5, unit: "ML" },
    ],
  },
  {
    id: "svc-021",
    name: "Premium Wash",
    description:
      "Deep cleaning — foam + wax + tyre polish + light interior touch-up. Best finish. Shampoo usage: high (~20–30 ml per car).",
    defaultPrice: 1200,
    segmentPricing: {
      HATCHBACK: 950,
      SEDAN: 1200,
      SUV: 1500,
      LUXURY: 2400,
      MUV: 1700,
      COMPACT_SUV: 1350,
    },
    category: "Detailing",
    isActive: true,
    isHighEnd: false,
    incentivePercent: 3,
    consumptionProfile: [
      { partId: "prt-021", partName: "Car Shampoo", quantityPerCar: 25, unit: "ML" },
      { partId: "prt-022", partName: "Car Polish Wax (1L)", quantityPerCar: 18, unit: "ML" },
      { partId: "prt-023", partName: "Interior Cleaner (2L)", quantityPerCar: 40, unit: "ML" },
    ],
  },
  {
    id: "svc-018",
    name: "PPF Coating",
    description: "Paint Protection Film - full body protection",
    defaultPrice: 20000,
    segmentPricing: {
      HATCHBACK: 15000,
      SEDAN: 20000,
      SUV: 28000,
      LUXURY: 45000,
      MUV: 32000,
      COMPACT_SUV: 22000,
    },
    category: "Detailing",
    isActive: true,
    isHighEnd: true,
    incentivePercent: 10,
    reminderInterval: "6_MONTHS",
    reminderDurationMonths: 36,
    consumptionProfile: [
      { partId: "prt-025", partName: "PPF Film (sq.ft roll)", quantityPerCar: 1, unit: "NOS" },
      { partId: "prt-024", partName: "Microfiber Cloth", quantityPerCar: 2, unit: "NOS" },
    ],
  },
  {
    id: "svc-019",
    name: "Ceramic Coating",
    description: "Premium ceramic coating for long-lasting protection",
    defaultPrice: 25000,
    segmentPricing: {
      HATCHBACK: 18000,
      SEDAN: 25000,
      SUV: 35000,
      LUXURY: 55000,
      MUV: 40000,
      COMPACT_SUV: 28000,
    },
    category: "Detailing",
    isActive: true,
    isHighEnd: true,
    incentivePercent: 10,
    reminderInterval: "6_MONTHS",
    reminderDurationMonths: 24,
    consumptionProfile: [
      { partId: "prt-022", partName: "Car Polish Wax (1L)", quantityPerCar: 40, unit: "ML" },
      { partId: "prt-021", partName: "Car Shampoo", quantityPerCar: 10, unit: "ML" },
    ],
  },
  {
    id: "svc-020",
    name: "Interior Detailing",
    description: "Deep interior cleaning, leather conditioning, dashboard treatment",
    defaultPrice: 4500,
    segmentPricing: {
      HATCHBACK: 3500,
      SEDAN: 4500,
      SUV: 6000,
      LUXURY: 9500,
      MUV: 7000,
      COMPACT_SUV: 5200,
    },
    category: "Detailing",
    isActive: true,
    isHighEnd: true,
    incentivePercent: 8,
    reminderInterval: "YEARLY",
    reminderDurationMonths: 12,
    consumptionProfile: [
      { partId: "prt-023", partName: "Interior Cleaner (2L)", quantityPerCar: 150, unit: "ML" },
      { partId: "prt-022", partName: "Car Polish Wax (1L)", quantityPerCar: 25, unit: "ML" },
      { partId: "prt-024", partName: "Microfiber Cloth", quantityPerCar: 2, unit: "NOS" },
    ],
  },
];
