import type { User } from "@/types";

export const staff: User[] = [
  {
    id: "usr-001",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@primedetailers.in",
    phone: "+91-9876543210",
    role: "SUPER_ADMIN",
    branchId: "br-001",
    isActive: true,
    attendancePin: "1001",
    emailVerified: true,
  },
  {
    id: "usr-002",
    name: "Priya Sharma",
    email: "priya.sharma@primedetailers.in",
    phone: "+91-9876543211",
    role: "ADMIN",
    branchId: "br-001",
    isActive: true,
    attendancePin: "1002",
  },
  {
    id: "usr-003",
    name: "Suresh Reddy",
    email: "suresh.reddy@primedetailers.in",
    phone: "+91-9876543212",
    role: "BRANCH_MANAGER",
    branchId: "br-001",
    isActive: true,
    attendancePin: "1003",
    emailVerified: true,
  },
  {
    id: "usr-004",
    name: "Anitha Nair",
    email: "anitha.nair@primedetailers.in",
    phone: "+91-9876543213",
    role: "RECEPTIONIST",
    branchId: "br-001",
    isActive: true,
    attendancePin: "1004",
  },
  {
    id: "usr-005",
    name: "Vikram Singh",
    email: "vikram.singh@primedetailers.in",
    phone: "+91-9876543214",
    role: "RECEPTIONIST",
    branchId: "br-002",
    isActive: true,
    attendancePin: "1005",
  },
  {
    id: "usr-006",
    name: "Murugan P",
    email: "murugan.p@primedetailers.in",
    phone: "+91-9876543215",
    role: "MECHANIC",
    branchId: "br-001",
    isActive: true,
    attendancePin: "1006",
    totalJobsCompleted: 42,
    totalIncentiveEarned: 18500,
  },
  {
    id: "usr-007",
    name: "Ramesh Gowda",
    email: "ramesh.gowda@primedetailers.in",
    phone: "+91-9876543216",
    role: "MECHANIC",
    branchId: "br-001",
    isActive: true,
    attendancePin: "1007",
    totalJobsCompleted: 38,
    totalIncentiveEarned: 16200,
  },
  {
    id: "usr-008",
    name: "Karthik Iyer",
    email: "karthik.iyer@primedetailers.in",
    phone: "+91-9876543217",
    role: "SUPERVISOR",
    branchId: "br-001",
    isActive: true,
    attendancePin: "1008",
    totalJobsCompleted: 35,
    totalIncentiveEarned: 14800,
  },
  {
    id: "usr-009",
    name: "Venkatesh M",
    email: "venkatesh.m@primedetailers.in",
    phone: "+91-9876543218",
    role: "MECHANIC",
    branchId: "br-002",
    isActive: true,
    attendancePin: "1009",
    totalJobsCompleted: 28,
    totalIncentiveEarned: 11200,
  },
  {
    id: "usr-010",
    name: "Prakash Rao",
    email: "prakash.rao@primedetailers.in",
    phone: "+91-9876543219",
    role: "MECHANIC",
    branchId: "br-002",
    isActive: true,
    attendancePin: "1010",
    totalJobsCompleted: 22,
    totalIncentiveEarned: 8900,
  },
];
