import type { Vehicle } from "@/types";

export const vehicles: Vehicle[] = [
  {
    id: "veh-001",
    customerId: "cust-001",
    customerName: "Arun Mehta",
    registrationNumber: "KA-01-AB-1234",
    make: "Maruti",
    model: "Swift",
    variant: "VXI",
    fuelType: "PETROL",
    color: "Pearl Arctic White",
    year: 2022,
    segment: "HATCHBACK",
  },
  {
    id: "veh-002",
    customerId: "cust-002",
    customerName: "Lakshmi Venkatesh",
    registrationNumber: "KA-02-CD-5678",
    make: "Hyundai",
    model: "Creta",
    variant: "SX",
    fuelType: "DIESEL",
    color: "Titan Grey",
    year: 2023,
    segment: "SUV",
  },
  {
    id: "veh-003",
    customerId: "cust-003",
    customerName: "Sandeep Patel",
    registrationNumber: "KA-03-EF-9012",
    make: "Tata",
    model: "Nexon",
    variant: "XZ+",
    fuelType: "PETROL",
    color: "Calcutta Teal",
    year: 2024,
    segment: "SUV",
  },
  {
    id: "veh-004",
    customerId: "cust-004",
    customerName: "Kavitha Krishnan",
    registrationNumber: "KA-04-GH-3456",
    make: "Honda",
    model: "City",
    variant: "VX",
    fuelType: "PETROL",
    color: "Radiant Red",
    year: 2021,
    segment: "SEDAN",
  },
  {
    id: "veh-005",
    customerId: "cust-005",
    customerName: "Mohammed Irfan",
    registrationNumber: "KA-05-IJ-7890",
    make: "Toyota",
    model: "Innova Crysta",
    variant: "GX",
    fuelType: "DIESEL",
    color: "Super White",
    year: 2022,
    segment: "MUV",
  },
  {
    id: "veh-006",
    customerId: "cust-006",
    customerName: "Deepa Nambiar",
    registrationNumber: "KA-06-KL-2345",
    make: "Mahindra",
    model: "XUV700",
    variant: "AX7",
    fuelType: "DIESEL",
    color: "Midnight Black",
    year: 2023,
    segment: "SUV",
  },
  {
    id: "veh-007",
    customerId: "cust-007",
    customerName: "Ravi Shankar",
    registrationNumber: "KA-01-MN-6789",
    make: "Maruti",
    model: "Baleno",
    variant: "Alpha",
    fuelType: "PETROL",
    color: "Nexa Blue",
    year: 2022,
    segment: "HATCHBACK",
  },
  {
    id: "veh-008",
    customerId: "cust-008",
    customerName: "Meera Sundaram",
    registrationNumber: "KA-02-OP-0123",
    make: "Hyundai",
    model: "i20",
    variant: "Sportz",
    fuelType: "PETROL",
    color: "Fiery Red",
    year: 2023,
    segment: "HATCHBACK",
  },
  {
    id: "veh-009",
    customerId: "cust-009",
    customerName: "Vijay Bhaskar",
    registrationNumber: "KA-03-QR-4567",
    make: "Tata",
    model: "Harrier",
    variant: "XZ",
    fuelType: "DIESEL",
    color: "Oberon Black",
    year: 2024,
    segment: "SUV",
  },
  {
    id: "veh-010",
    customerId: "cust-010",
    customerName: "Shalini Desai",
    registrationNumber: "KA-04-ST-8901",
    make: "Maruti",
    model: "Brezza",
    variant: "VXI+",
    fuelType: "PETROL",
    color: "Nexa Blue",
    year: 2023,
    segment: "COMPACT_SUV",
    previousOwners: [
      {
        customerId: "cust-003",
        customerName: "Sandeep Patel",
        transferDate: "2025-06-15",
      },
    ],
  },
  {
    id: "veh-011",
    customerId: "cust-001",
    customerName: "Arun Mehta",
    registrationNumber: "KA-05-UV-2345",
    make: "Honda",
    model: "Amaze",
    variant: "VX",
    fuelType: "DIESEL",
    color: "Modern Steel",
    year: 2020,
    notes: "Second car - used for city commute",
    segment: "SEDAN",
  },
  {
    id: "veh-012",
    customerId: "cust-011",
    customerName: "Ganesh Prasad",
    registrationNumber: "KA-06-WX-6789",
    make: "Kia",
    model: "Seltos",
    variant: "HTK+",
    fuelType: "PETROL",
    color: "Intelligence Orange",
    year: 2023,
    segment: "SUV",
  },
  {
    id: "veh-013",
    customerId: "cust-012",
    customerName: "Anjali Menon",
    registrationNumber: "KA-01-YZ-0123",
    make: "Hyundai",
    model: "Venue",
    variant: "SX",
    fuelType: "DIESEL",
    color: "Polar White",
    year: 2022,
    segment: "COMPACT_SUV",
  },
  {
    id: "veh-014",
    customerId: "cust-013",
    customerName: "Srinivas Rao",
    registrationNumber: "KA-02-AA-4567",
    make: "Maruti",
    model: "Ertiga",
    variant: "VXI",
    fuelType: "PETROL",
    color: "Nexa Blue",
    year: 2021,
    segment: "MUV",
  },
  {
    id: "veh-015",
    customerId: "cust-014",
    customerName: "Pooja Gupta",
    registrationNumber: "KA-03-BB-8901",
    make: "Tata",
    model: "Punch",
    variant: "Creative",
    fuelType: "PETROL",
    color: "Daytona Grey",
    year: 2024,
    segment: "HATCHBACK",
  },
  {
    id: "veh-016",
    customerId: "cust-015",
    customerName: "Kiran Shetty",
    registrationNumber: "KA-04-CC-2345",
    make: "Toyota",
    model: "Fortuner",
    variant: "Legender",
    fuelType: "DIESEL",
    color: "Super White",
    year: 2023,
    segment: "SUV",
  },
  {
    id: "veh-017",
    customerId: "cust-016",
    customerName: "Divya Rajan",
    registrationNumber: "KA-05-DD-6789",
    make: "MG",
    model: "Hector",
    variant: "Sharp",
    fuelType: "PETROL",
    color: "Candy White",
    year: 2022,
    segment: "SUV",
  },
  {
    id: "veh-018",
    customerId: "cust-017",
    customerName: "Manish Agarwal",
    registrationNumber: "KA-06-EE-0123",
    make: "Mahindra",
    model: "Thar",
    variant: "LX",
    fuelType: "DIESEL",
    color: "Rocky Beige",
    year: 2024,
    segment: "SUV",
  },
  {
    id: "veh-019",
    customerId: "cust-018",
    customerName: "Rekha Pillai",
    registrationNumber: "KA-01-FF-4567",
    make: "Maruti",
    model: "Wagon R",
    variant: "ZXI+",
    fuelType: "CNG",
    color: "Metallic Magma Grey",
    year: 2023,
    segment: "HATCHBACK",
  },
  {
    id: "veh-020",
    customerId: "cust-003",
    customerName: "Sandeep Patel",
    registrationNumber: "KA-02-GG-8901",
    make: "Hyundai",
    model: "Verna",
    variant: "SX",
    fuelType: "PETROL",
    color: "Titan Grey",
    year: 2022,
    segment: "SEDAN",
  },
  {
    id: "veh-021",
    customerId: "cust-007",
    customerName: "Ravi Shankar",
    registrationNumber: "KA-03-HH-2345",
    make: "Honda",
    model: "Elevate",
    variant: "VX",
    fuelType: "PETROL",
    color: "Radiant Red",
    year: 2024,
    segment: "COMPACT_SUV",
  },
  {
    id: "veh-022",
    customerId: "cust-009",
    customerName: "Vijay Bhaskar",
    registrationNumber: "KA-04-II-6789",
    make: "Skoda",
    model: "Kushaq",
    variant: "Style",
    fuelType: "PETROL",
    color: "Candy White",
    year: 2023,
    segment: "SUV",
  },
  {
    id: "veh-023",
    customerId: "cust-005",
    customerName: "Mohammed Irfan",
    registrationNumber: "KA-05-JJ-0123",
    make: "Maruti",
    model: "Alto",
    variant: "VXI+",
    fuelType: "PETROL",
    color: "Silky Silver",
    year: 2021,
    segment: "HATCHBACK",
  },
  {
    id: "veh-024",
    customerId: "cust-012",
    customerName: "Anjali Menon",
    registrationNumber: "KA-06-KK-4567",
    make: "Tata",
    model: "Tiago",
    variant: "XZ+",
    fuelType: "PETROL",
    color: "Stadium Grey",
    year: 2022,
    segment: "HATCHBACK",
  },
  {
    id: "veh-025",
    customerId: "cust-015",
    customerName: "Kiran Shetty",
    registrationNumber: "KA-01-LL-8901",
    make: "Volkswagen",
    model: "Taigun",
    variant: "Highline",
    fuelType: "PETROL",
    color: "Carbon Steel Grey",
    year: 2023,
    segment: "SUV",
  },
  {
    id: "veh-026",
    customerId: "cust-002",
    customerName: "Lakshmi Venkatesh",
    registrationNumber: "KA-02-MM-2345",
    make: "Maruti",
    model: "Grand Vitara",
    variant: "Alpha+",
    fuelType: "HYBRID",
    color: "Nexa Blue",
    year: 2024,
    segment: "MUV",
  },
  {
    id: "veh-027",
    customerId: "cust-008",
    customerName: "Meera Sundaram",
    registrationNumber: "KA-03-NN-6789",
    make: "Tata",
    model: "EV",
    variant: "XZ+ Lux",
    fuelType: "ELECTRIC",
    color: "Teal Blue",
    year: 2024,
    segment: "HATCHBACK",
  },
  {
    id: "veh-028",
    customerId: "cust-017",
    customerName: "Manish Agarwal",
    registrationNumber: "KA-04-OO-0123",
    make: "Hyundai",
    model: "Creta",
    variant: "SX(O)",
    fuelType: "PETROL",
    color: "Abyss Black",
    year: 2023,
    segment: "SUV",
  },
  {
    id: "veh-029",
    customerId: "cust-004",
    customerName: "Kavitha Krishnan",
    registrationNumber: "KA-05-PP-4567",
    make: "Kia",
    model: "Carens",
    variant: "Prestige",
    fuelType: "DIESEL",
    color: "Sparkling Silver",
    year: 2023,
    segment: "MUV",
  },
  {
    id: "veh-030",
    customerId: "cust-010",
    customerName: "Shalini Desai",
    registrationNumber: "KA-06-QQ-8901",
    make: "Maruti",
    model: "Fronx",
    variant: "Delta+",
    fuelType: "PETROL",
    color: "Nexa Blue",
    year: 2024,
    segment: "HATCHBACK",
  },
];
